version: '3'
services:
  emacs-rpm:
    build: ./
    # privileged: true
    image: emacs-rpm
    container_name: emacs-rpm
    # restart: unless-stopped
    volumes:
      - ./make_pkg.sh:/root/make_pkg.sh
    # expose:
    #   - "3000"
    # ports:
    #   - "0.0.0.0:3000:3000"
    tty: true
